# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-02-13 17:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('z_score', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MonthlyWeatherByCity',
            new_name='Monthly',
        ),
    ]
