# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-02-13 19:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('z_score', '0003_dailyweather'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DailyWeather',
            new_name='Daily',
        ),
    ]
